-- ============================================================
-- 중독백과: '알맹이' 보강 통합 패치 (한/영)
-- (1) 12단계 실제 단계  (2) SMART 4도구/평온기도문/스위스 4기둥/DSM 11기준/MI OARS
-- (3) 인물 6명 기본 사실(빌W·닥터밥·러시·융·옐리네크·볼코)
-- 모두 jsonb_insert 로 문단 삽입, 기존 내용 보존. 저작권 문구 복제 없음.
-- 실행: psql -h localhost -U postgres -d addiction_news -f inject_essentials_all.sql
-- 멱등: 동일 제목 문단이 이미 있으면 해당 UPDATE는 건너뜀(WHERE NOT EXISTS).
-- ============================================================
BEGIN;

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "12단계는 어떤 단계인가", "p": "12단계는 크게 세 흐름으로 이해할 수 있다. 먼저 인정과 내맡김이다. ①중독 앞에서 자신이 무력함을 인정하고, ②자기를 넘어선 더 큰 힘의 도움을 믿으며, ③그 힘에 자신을 맡기기로 결심한다. 다음은 성찰과 정리다. ④두려움 없이 자신을 도덕적으로 살펴보고, ⑤그 잘못을 자신과 타인, 그리고 더 큰 존재 앞에 솔직히 인정하며, ⑥⑦자신의 결점을 내려놓을 준비를 하고 그것이 사라지기를 겸손히 구한다. 마지막은 관계 회복과 실천이다. ⑧자신이 해를 끼친 사람들의 목록을 만들어 ⑨가능한 한 직접 보상하고(단, 그로 인해 누군가 다치지 않는 한), ⑩계속 자신을 살펴 잘못이 있으면 즉시 인정하며, ⑪기도와 성찰로 영적 접촉을 이어가고, ⑫이 각성을 바탕으로 다른 중독자를 돕고 이 원리를 삶의 모든 영역에서 실천한다. 특정 종교의 교리가 아니라 ''자기를 넘어선 힘''에 대한 열린 이해 위에 서 있어, 각자의 신앙이나 세계관에 맞춰 받아들일 수 있도록 설계되어 있다."}'::jsonb), updated_at=now() WHERE id='twelve-step' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='12단계는 어떤 단계인가');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "What are the twelve steps", "p": "The twelve steps can be understood in three broad movements. First comes admission and surrender: (1) admitting powerlessness over the addiction, (2) coming to believe that a power greater than oneself can help, and (3) deciding to turn oneself over to that power. Next comes reflection and reckoning: (4) making a fearless moral inventory of oneself, (5) admitting those wrongs honestly to oneself, to others, and to a greater being, and (6-7) becoming ready to let go of one''s defects and humbly asking that they be removed. Last comes repairing relationships and practice: (8) listing the people one has harmed and (9) making direct amends wherever possible, except when doing so would injure someone, (10) continuing to take personal inventory and promptly admitting wrongs, (11) sustaining spiritual contact through prayer and reflection, and (12) carrying this awakening to help other addicts and practicing these principles in all areas of life. Standing on an open understanding of a ''power greater than oneself'' rather than the doctrine of any particular religion, it is designed to be received in accordance with each person''s own faith or worldview."}'::jsonb), updated_at=now() WHERE id='twelve-step' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='What are the twelve steps');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "네 가지 도구", "p": "SMART 리커버리는 네 영역의 도구를 중심으로 한다. ①동기 쌓고 유지하기(변화의 득실을 따져 변화 동기를 다진다), ②충동에 대처하기(갈망을 알아차리고 견디는 기술), ③생각·감정·행동 다루기(비합리적 신념을 검토하고 감정을 조절한다), ④균형 잡힌 삶 살기(단약 이후 의미 있고 균형 잡힌 삶을 세운다). 12단계와 달리 ''평생 회복 중''이라는 정체성보다 문제 해결과 자립을 지향하며, 인지행동치료와 동기강화의 원리를 실용적 도구로 풀어낸 것이 특징이다."}'::jsonb), updated_at=now() WHERE id='smart-recovery' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='네 가지 도구');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "The four tools", "p": "SMART Recovery centers on tools in four areas: (1) building and maintaining motivation (weighing the costs and benefits of change to strengthen the motive to change), (2) coping with urges (skills to notice and endure cravings), (3) managing thoughts, feelings, and behaviors (examining irrational beliefs and regulating emotion), and (4) living a balanced life (building a meaningful, balanced life beyond abstinence). Unlike the twelve steps, it orients toward problem-solving and self-reliance rather than a lifelong ''in recovery'' identity, translating the principles of cognitive-behavioral therapy and motivation into practical tools."}'::jsonb), updated_at=now() WHERE id='smart-recovery' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='The four tools');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "기도문", "p": "가장 널리 쓰이는 짧은 형태는 이렇게 옮길 수 있다. \"바꿀 수 없는 것을 받아들이는 평온을, 바꿀 수 있는 것을 바꾸는 용기를, 그리고 그 둘을 분별하는 지혜를 주소서.\" 라인홀드 니버가 지은 것으로 알려진 이 기도는 원래 더 긴 형태이지만, 회복 모임에서는 주로 이 세 구절이 낭송된다. 핵심은 통제할 수 없는 것(과거·타인·결과)에 대한 집착을 내려놓고, 지금 할 수 있는 것에 힘을 모으며, 그 둘을 분별하는 지혜를 구하는 데 있다."}'::jsonb), updated_at=now() WHERE id='serenity-prayer' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='기도문');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "The prayer", "p": "The most widely used short form can be rendered: \"Grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference.\" Attributed to Reinhold Niebuhr, the prayer originally had a longer form, but recovery meetings mainly recite these three lines. Its core is releasing attachment to what cannot be controlled (the past, other people, outcomes), gathering one''s strength for what can be done now, and seeking the wisdom to tell the two apart."}'::jsonb), updated_at=now() WHERE id='serenity-prayer' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='The prayer');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "네 개의 기둥", "p": "네 기둥은 각각 이렇다. ①예방(사용을 시작하지 않도록 교육·환경 개선), ②치료(의존에서 벗어나도록 돕는 다양한 치료와 대체요법), ③피해감소(사용을 당장 멈추지 못하더라도 죽거나 병들지 않도록 주사기 교환·안전소비시설·헤로인 처방 등으로 해악을 줄임), ④법집행·규제(공급과 조직범죄를 통제하되 사용자를 무조건 처벌하기보다 보건으로 연결). 핵심은 어느 하나에 치우치지 않고 네 기둥을 균형 있게 세운다는 것이며, 이 통합성이 스위스 모델의 성공 요인으로 꼽힌다."}'::jsonb), updated_at=now() WHERE id='swiss-four-pillars' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='네 개의 기둥');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "The four pillars", "p": "The four pillars are: (1) prevention (education and environmental improvement so use does not begin), (2) treatment (varied therapies and substitution treatment to help people out of dependence), (3) harm reduction (reducing harm through needle exchange, supervised consumption, heroin prescription, and the like so that people do not die or fall ill even if they cannot stop immediately), and (4) law enforcement and regulation (controlling supply and organized crime while connecting users to health services rather than simply punishing them). The core is setting up all four in balance rather than leaning on any one, and this integration is cited as the key to the Swiss model''s success."}'::jsonb), updated_at=now() WHERE id='swiss-four-pillars' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='The four pillars');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{3}', '{"h": "11개 진단 기준", "p": "DSM-5-TR 의 물질사용장애는 열한 가지 기준을 바탕으로 하며, 크게 네 묶음으로 나뉜다. 통제 손상(의도보다 많이·오래 사용, 줄이려는 실패한 시도, 구하고 쓰는 데 많은 시간, 강한 갈망), 사회적 손상(역할 수행 실패, 문제가 생기는데도 계속, 중요한 활동을 포기), 위험한 사용(위험한 상황에서도 사용, 해가 되는 줄 알면서도 지속), 약리적 지표(내성, 금단). 해당하는 기준이 2~3개면 경도, 4~5개면 중등도, 6개 이상이면 고도로 심각도를 나눈다. 핵심은 ''얼마나 쓰는가''가 아니라 통제 상실과 기능 손상의 개수라는 점이다."}'::jsonb), updated_at=now() WHERE id='dsm' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='11개 진단 기준');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{3}', '{"h": "The eleven diagnostic criteria", "p": "Substance use disorder in DSM-5-TR rests on eleven criteria, grouped into four clusters. Impaired control (using more or longer than intended, failed attempts to cut down, much time spent obtaining and using, strong craving); social impairment (failure to fulfill roles, continuing despite problems, giving up important activities); risky use (using in hazardous situations, continuing despite knowing the harm); and pharmacological markers (tolerance, withdrawal). Severity is graded by the number of criteria met: 2-3 mild, 4-5 moderate, 6 or more severe. The key is that it is the number of signs of lost control and functional impairment, not ''how much one uses.''"}'::jsonb), updated_at=now() WHERE id='dsm' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='The eleven diagnostic criteria');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{3}', '{"h": "핵심 기법(OARS)", "p": "동기강화상담의 기본 기법은 흔히 OARS 로 요약된다. ①열린 질문(예/아니오로 끝나지 않는 질문으로 스스로 말하게 함), ②인정(당사자의 강점과 노력을 진심으로 짚어줌), ③반영적 경청(들은 것을 되비추어 이해를 확인하고 깊이를 더함), ④요약(대화를 간추려 변화의 방향을 모음). 여기에 당사자의 ''변화대화''(바꾸고 싶다는 말)를 알아차리고 강화하는 것이 핵심이다. 상담자는 답을 주는 사람이 아니라, 당사자가 스스로 답을 찾도록 돕는 동반자의 자리에 선다."}'::jsonb), updated_at=now() WHERE id='motivational-interviewing' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='핵심 기법(OARS)');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{3}', '{"h": "Core skills (OARS)", "p": "The basic skills of motivational interviewing are often summarized as OARS: (1) Open questions (questions that do not end in yes/no, prompting the person to speak), (2) Affirmations (sincerely acknowledging the person''s strengths and efforts), (3) Reflective listening (mirroring back what was heard to confirm understanding and add depth), and (4) Summaries (condensing the conversation to gather the direction of change). Central to this is noticing and reinforcing the person''s ''change talk'' (statements of wanting to change). The counselor stands not as one who gives answers but as a companion helping the person find their own."}'::jsonb), updated_at=now() WHERE id='motivational-interviewing' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='Core skills (OARS)');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "기본 사실", "p": "빌 윌슨(William Griffith Wilson, 1895~1971)은 미국의 주식 중개인이었다. 오랜 알코올 문제로 고통받다 1934년 회복을 경험했고, 1935년 오하이오주 애크런에서 의사 로버트 스미스(닥터 밥)를 만나 함께 익명의 알코올중독자(AA)를 세웠다. 1939년 회복 방법을 담은 책 『익명의 알코올중독자』(통칭 ''빅북'')를 펴냈고, 여기서 12단계가 제시되었다. 익명 전통에 따라 생전에 ''빌 W.''로만 불렸다."}'::jsonb), updated_at=now() WHERE id='bill-w' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='기본 사실');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "Basic facts", "p": "Bill Wilson (William Griffith Wilson, 1895-1971) was an American stockbroker. After long suffering from alcohol problems, he experienced recovery in 1934, and in 1935 in Akron, Ohio he met the physician Robert Smith (Dr. Bob) and together they founded Alcoholics Anonymous (AA). In 1939 he published the book Alcoholics Anonymous (known as the ''Big Book''), which set out the twelve steps. In keeping with the tradition of anonymity, he was known during his life only as ''Bill W.''"}'::jsonb), updated_at=now() WHERE id='bill-w' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='Basic facts');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "기본 사실", "p": "닥터 밥(Robert Holbrook Smith, 1879~1950)은 미국 오하이오주의 외과의사였다. 자신도 알코올 문제를 겪던 중 1935년 빌 윌슨을 만나 회복했고, 두 사람이 함께 AA를 창립했다. 의사라는 전문성과 당사자라는 위치를 겸한 그는, 초기 AA에서 알코올중독자들을 직접 도우며 상호원조 회복을 실천으로 구현했다."}'::jsonb), updated_at=now() WHERE id='dr-bob' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='기본 사실');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "Basic facts", "p": "Dr. Bob (Robert Holbrook Smith, 1879-1950) was a surgeon in Ohio, USA. While struggling with his own alcohol problems, he met Bill Wilson in 1935 and recovered, and together the two founded AA. Combining the expertise of a physician with the standing of a person in recovery, he directly helped alcoholics in AA''s early days, embodying mutual-aid recovery in practice."}'::jsonb), updated_at=now() WHERE id='dr-bob' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='Basic facts');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "기본 사실", "p": "벤저민 러시(Benjamin Rush, 1746~1813)는 미국 건국기의 의사이자 미국 독립선언서 서명자 중 한 명이다. 1780년대에 만성 과음을 ''의지의 악덕''이 아니라 일종의 질병으로 보아야 한다는 견해를 담은 글을 남겼는데, 이는 중독을 질병으로 이해하는 관점의 아주 이른 역사적 뿌리로 꼽힌다. 다만 그의 여러 다른 의학적 견해는 오늘날 기준으로는 낡은 것이었다."}'::jsonb), updated_at=now() WHERE id='benjamin-rush' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='기본 사실');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "Basic facts", "p": "Benjamin Rush (1746-1813) was a physician of America''s founding era and a signer of the Declaration of Independence. In the 1780s he wrote that chronic heavy drinking should be seen not as a ''vice of the will'' but as a kind of disease—cited as a very early historical root of understanding addiction as illness. Many of his other medical views, however, were outdated by today''s standards."}'::jsonb), updated_at=now() WHERE id='benjamin-rush' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='Basic facts');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "기본 사실", "p": "카를 융(Carl Gustav Jung, 1875~1961)은 스위스의 정신의학자이자 분석심리학의 창시자다. 한 알코올중독 환자에게 의학적 치료를 넘어선 영적 각성이 회복에 필요할 수 있다는 견해를 전한 것으로 알려져 있으며, 이 생각이 빌 윌슨을 거쳐 AA 초기의 영적 틀 형성에 간접적 영향을 준 것으로 이야기된다."}'::jsonb), updated_at=now() WHERE id='carl-jung' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='기본 사실');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "Basic facts", "p": "Carl Jung (Carl Gustav Jung, 1875-1961) was a Swiss psychiatrist and the founder of analytical psychology. He is known to have suggested to one alcoholic patient that a spiritual awakening beyond medical treatment might be needed for recovery, and this idea is said to have indirectly influenced, via Bill Wilson, the shaping of AA''s early spiritual framework."}'::jsonb), updated_at=now() WHERE id='carl-jung' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='Basic facts');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "기본 사실", "p": "E. M. 옐리네크(Elvin Morton Jellinek, 1890~1963)는 알코올중독을 과학적 연구의 대상으로 정립한 초기 연구자다. 알코올중독의 진행을 단계로 설명하는 ''옐리네크 곡선''을 제시하고, 1960년 『알코올중독이라는 질병 개념』을 펴내 질병모델의 학문적 토대를 놓았다. 그의 유형·단계 구분은 큰 영향을 미쳤으나 이후 지나친 일반화라는 비판도 받았다."}'::jsonb), updated_at=now() WHERE id='jellinek' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='기본 사실');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "Basic facts", "p": "E. M. Jellinek (Elvin Morton Jellinek, 1890-1963) was an early researcher who established alcoholism as an object of scientific study. He proposed the ''Jellinek curve'' describing the progression of alcoholism in stages, and in 1960 published The Disease Concept of Alcoholism, laying the scholarly foundation of the disease model. His typology and staging were highly influential but later criticized as over-generalized."}'::jsonb), updated_at=now() WHERE id='jellinek' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='Basic facts');

UPDATE encyclopedia_terms SET body=jsonb_insert(body, '{1}', '{"h": "기본 사실", "p": "노라 볼코(Nora Volkow, 1956~)는 멕시코 태생의 미국 정신과의사로, 2003년부터 미국 국립약물남용연구소(NIDA) 소장을 맡고 있다. 뇌영상 연구를 통해 중독이 뇌의 보상·자기통제 회로를 변화시키는 뇌질환임을 규명하는 데 크게 기여했다. 소장으로서 낙인·범죄화·건강 불평등이 중독을 악화시키는 방식을 다루는 정책을 강조해 왔다."}'::jsonb), updated_at=now() WHERE id='nora-volkow' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body) e WHERE e->>'h'='기본 사실');

UPDATE encyclopedia_terms SET body_en=jsonb_insert(body_en, '{1}', '{"h": "Basic facts", "p": "Nora Volkow (1956-) is a Mexican-born American psychiatrist who has served since 2003 as director of the U.S. National Institute on Drug Abuse (NIDA). Through brain-imaging research she has contributed greatly to establishing that addiction is a brain disorder that alters the brain''s reward and self-control circuits. As director she has emphasized policies addressing how stigma, criminalization, and health disparities worsen addiction."}'::jsonb), updated_at=now() WHERE id='nora-volkow' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(body_en) e WHERE e->>'h'='Basic facts');

COMMIT;

SELECT id, jsonb_array_length(body) ko, jsonb_array_length(body_en) en
FROM encyclopedia_terms
WHERE id IN (
  'twelve-step','smart-recovery','serenity-prayer','swiss-four-pillars',
  'dsm','motivational-interviewing','bill-w','dr-bob','benjamin-rush',
  'carl-jung','jellinek','nora-volkow'
)
ORDER BY id;
